Tesor Transporition

In [18]:
import pandas as pd
import numpy as np

x = np.array([[25,2], [5,26], [3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [19]:
x.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [20]:
import tensorflow as tf
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

## Arithmetic

In [21]:
x * 2


array([[50,  4],
       [10, 52],
       [ 6, 14]])

## Hadamard Product or The element-wise product
if two tensors have the same size, operations are ofthern by default applied element-wise

In [22]:
A = x +2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [23]:
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [24]:
A * x

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])