Every algorithm is exposed in scikit-learn va an "Estimator"

###  Step 1: Import the model
from sklearn.family import Model

In [ ]:
from sklearn.linear_model import LinearRegression

Estimator parameter: All the parameters of an estimator can be set when it is instantiated, and have suitable default values
- Make sure we split the data to train and test data

In [ ]:
# example model with LinearRegression
model = LinearRegression(normalize=True)
print(model)

In [ ]:
LinearRegression(copy_X=True, fit_intercept=True, normalize=True)

### Step2: Once we have the model created with our parameters, we can fit the model on some data

In [11]:
import numpy as np
# from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5,2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
list(y)


[0, 1, 2, 3, 4]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [15]:
X_test

array([[2, 3],
       [8, 9]])

In [16]:
y_train

[2, 0, 3]

In [17]:
y_test

[1, 4]

In [18]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]

### Step 3: Train/ Fit our model on the training data
After we split the data, we can train/fit our model on the training data

In [ ]:
model.fit(X_train, y_train)

### Step 4: Predict
The model has been fit and trained on the training data. The model is ready to predict labels or values on the test set

In [ ]:
predictions = model.predict(X_test)

### Step 5: Evaluate our model
Comparing our predictions to the correct values.
The evaluation method depends on what sort of machine learning algorithms we are using(Regression, Classification, clustering, ect.)