# Basic Tensor Arithmetic

In [11]:
import numpy as np
x = np.array([[25,2],[5,26],[3,7]])


In [12]:
x*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [13]:
x+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [14]:
x*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

## PyTorch
Python operators are overloaded; could alternatively use torch.mul() or torch.add()

In [15]:
import torch
x_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
x_pt * 2+3

tensor([[53,  7],
        [13, 55],
        [ 9, 17]])

In [16]:
torch.add(torch.mul(x_pt, 2),3)

tensor([[53,  7],
        [13, 55],
        [ 9, 17]])

In [18]:
A = x_pt + 2
A

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [19]:
A + x_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])