In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:4]

array([0, 1, 2, 3])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]
# grab after index 5(which below 6 in acutally index 6!)

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
# reset array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99

In [21]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

NameError: name 'arr_copy' is not defined