In [39]:
import numpy as np

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:4]

array([0, 1, 2, 3])

In [45]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arr[5:]
# grab after index 5(which below 6 in acutally index 6!)

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
# reset array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:] = 99

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [58]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
# getting the row 0 and column 2
arr_2d[0][2]

15

In [60]:
arr_2d[1][1]

25

In [61]:
arr_2d[2][1]

40

In [64]:
# more recommend this way using commar 
arr_2d[1,2]
# same as arr_2d[1][2]

30

In [65]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [68]:
# get everything before row 2
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [69]:
# then everyhing from column 1
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr_new2D = np.array([[4,34,45,21],[66,16,8, 8],[11,77,11,77],[77,97,6,55]])
arr_new2D

array([[ 4, 34, 45, 21],
       [66, 16,  8,  8],
       [11, 77, 11, 77],
       [77, 97,  6, 55]])

In [73]:
arr_new2D[2: , 2:]

array([[11, 77],
       [ 6, 55]])

In [76]:
fruit = np.arange(1,11)
fruit

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
fruit > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [80]:
bool_arr = fruit > 8
fruit[bool_arr]

array([ 9, 10])

In [82]:
fruit[fruit>8]

array([ 9, 10])

In [83]:
another2d = np.arange(50).reshape(5,10)
another2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
another2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [87]:
another2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [88]:
another2d[2:4, 6:9]

array([[26, 27, 28],
       [36, 37, 38]])