In [1]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
arr

array([1, 2, 3])

In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [12]:
np.random.rand(5)

array([0.39149714, 0.14403112, 0.81788218, 0.37069186, 0.00589796])

In [13]:
np.random.rand(5,2)

array([[0.72064571, 0.08269071],
       [0.4804106 , 0.0673948 ],
       [0.61314757, 0.38652646],
       [0.89457031, 0.68705821],
       [0.69263348, 0.33304727]])

In [18]:
np.random.randn(2,2)

array([[-1.19668857,  1.18145006],
       [-0.43509437, -1.81179677]])

In [35]:
np.random.randint(1,101)

74

In [36]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 3, 23, 28,  6,  3,  0, 16, 42, 28, 38])

In [43]:
arr.reshape(5,5)
# this method only if we fill the array. if that is extra space that will return error. 
# to check that. we could do the number of column muliply row equal len of the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranarr.max()

42

In [52]:
# to return index of max value in array
ranarr.argmax()

7

In [48]:
ranarr.min()

0

In [53]:
ranarr

array([ 3, 23, 28,  6,  3,  0, 16, 42, 28, 38])

In [56]:
arr.shape
# A COMMAR IN THE OUTPUT MEANING THAT IS ONE DIMENSION ARRAY

(25,)

In [57]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.shape

(5, 5)

In [59]:
arr.dtype

dtype('int32')

In [80]:
from numpy.random import randint
randint(2,10)

4